spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salesdb
    username: salesdb
    password: salesdb
  jpa:
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
    hibernate:
      ddl-auto: create